[package]
name = "ical-filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.3"
[dependencies.ical]
version = "0.8.*"
default-features = false
features = ["ical", "vcard"]
